language: node_js
node_js:
- '6'
- node
sudo: false
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: RsCgDg8gUMSCPctXSnEFQ0n4sLuD9/Ve5rNNXizLhplHqPN42wtC7Zkip34RerQcrgjAK+x2Chdo9Fj1AN7Ys+NObVMyUJu/2LlzMtKfYV24jTyShFDXtVOAbEfq88nAhQ6fd1fZlRm2yixerVz9YN5SVSDihTtI/5jtGEIt5F4ncE7Eta/QspaIuRWXziThIDkbScOe8mC23tnghda2HasH17ck+Tef8HmJdAGyn6yFB5b7PX1IPmD7JOL+yiqqn2/yDcJUdBwFk5gkJO3cOvwp1hfWbsjyY80yw1fzFOU1gNy2lHJ5VZGmZvQG4mqWc5axipr4KffnCxVaXr2DJ/58oG6lwSCoI5o1gUGLNasiYNSzXKTqjFfmmDvRRU6ba904zH1KbGHdN/y8eGmvMWqm4bL91gGZBw60ny6sQn1sOkfWEeQZDvqRd5wlzygZdxpJUJLvMIFsQaAZEPTksehLBrzaMST79rnikKYIy2JHgsuHPZxpvnqnS0I8FsjYGk/b5uYoxkK2qB6qg8j2x3gy+SMSp/Pbjphf/DEFfjFfq6GOdF6jA3TEH795OYkMTg1YxUngqHbSf6S/lBiwAHyp97WkOYGGMiXYaAp0ucxSmBEmUDJ2iI19tE7RVtFg5at7tDGIdKgLjzzElYeMeogXBpGXx1cjVKkninJCICI=
  on:
    tags: true
    repo: xogroup/toki-method-http
notifications:
  slack:
    secure: GyQRWHIhYkDWoMCF3h5I4SXXieRu/qZ5yS0I69cr8In4SJ2mxAErPwkzjMjMg2FkS8s4E8StUhF2lXuZcjHYxLow/rOCKegp6Wu7VJC5YBqo9s9IW0bsdjaB5i5gjeQxgTh2qJzSl/vZTthYDqCtCJpuLgFU5zls6nF4fpT8TOLqS/YmHnLHyHOpjURFlW2WeeaI878jcZYD7ZCut7h17OyGAYCA464LFHLcpdoxK5FFQCKhnE0YhG+gkP3msy0ImN7Fzn6feimLJTh/ZYJiXIQ1ONyRtO0aEvEjJ8M0j4UyxaL4Ps7itdfM1PF1fYqPwDpLPG1xKeDol3/tnAUpXMAnNow6pbfD8VCuN+IhbZREHGxk/0hBdIVs2HyX5bxkJDS4BvC63pVXCwXxE9+fXLIO79ysEiwAl7QAfB6E/ONzz3AKLNvWOV1WA0P6N3cMFoIa2KFT+P75h9BVC2tuf30ARideP91RsPlj7FDcnzBqiIj3Tpxx8ntoHMsG8nDfUusugelscay/lbrcV0wnl88uUCG+l3pZWw84fCWjGyDrC0/G71bcd94Nje1tp9V8HF8cGZISxEwIlfX3KWPLs5vnvVPljAht79hFxGrH1Ozk7wBChDceXJSlN6a9r70DoXRJlLya4RGzywgkcnSjCTNB9ln6aPGF1fY47i6TN24=
