language: node_js
node_js:
- '6'
- node
sudo: false
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: cjjRFQBHAAXuZeWUVdM/Ap6lFuzG8LDTqWE1wxX+Dth9rhyioJWyrWg2yD0+FRScog9R2/HHPELcssryOwSIuLJXL9AVe5pX+koLNkH4cJ997+uVUzQyR53FI7uQ+ZZv3WvFSBiprLhquAWYRGnfStkrXJYiIpolmhAOonzBaWhWB/0TFu5+zyls5/8oVROREdaNZB2Z+TtPVosT2Qtbol2PGOdw2PmQd6ByE+ECvvFR/Knxa0/91DS/+cJjS724ZEl9vUvx2xiyLg2csbwLurOhkNmU7zWVHGo4JOHpFUJR92Pp/8Pyg8dMNedJBBSK2o1UA60j4mHIZVgBmZywLACAKZChFjjK4OMqZaH3iSDttOtPEEFE7nGxj7tst/U3zLo5O629JQF95gVTSyKSoy6nDY/Bl2cgInYJgvps82F5+hb6BYTJW9z5TBmt4Xy5Cmq+aUxjaMxISrns58brEaTCEH75+JX0WdUnP6RlNP0we6WfKYPT5zkzo3Fqt3eWddeqYgNrmYc+tTTKeZ1dNfFpfkQlotwAWKElq2NF/NO3VDtUqQpSUtyjN0gFwdnurmXpYPU8fPKqzDzxVRSCYLiW9CT9cd5KVg2BowAXhyz/nNzkaKnI4yLFdRMjgRuzMiphseOq+341UEWBG4CbP6c0ZFFS2d5xvgAZZ2QCUyw=
  on:
    tags: true
    repo: xogroup/toki-method-http
notifications:
  slack:
    secure: GyQRWHIhYkDWoMCF3h5I4SXXieRu/qZ5yS0I69cr8In4SJ2mxAErPwkzjMjMg2FkS8s4E8StUhF2lXuZcjHYxLow/rOCKegp6Wu7VJC5YBqo9s9IW0bsdjaB5i5gjeQxgTh2qJzSl/vZTthYDqCtCJpuLgFU5zls6nF4fpT8TOLqS/YmHnLHyHOpjURFlW2WeeaI878jcZYD7ZCut7h17OyGAYCA464LFHLcpdoxK5FFQCKhnE0YhG+gkP3msy0ImN7Fzn6feimLJTh/ZYJiXIQ1ONyRtO0aEvEjJ8M0j4UyxaL4Ps7itdfM1PF1fYqPwDpLPG1xKeDol3/tnAUpXMAnNow6pbfD8VCuN+IhbZREHGxk/0hBdIVs2HyX5bxkJDS4BvC63pVXCwXxE9+fXLIO79ysEiwAl7QAfB6E/ONzz3AKLNvWOV1WA0P6N3cMFoIa2KFT+P75h9BVC2tuf30ARideP91RsPlj7FDcnzBqiIj3Tpxx8ntoHMsG8nDfUusugelscay/lbrcV0wnl88uUCG+l3pZWw84fCWjGyDrC0/G71bcd94Nje1tp9V8HF8cGZISxEwIlfX3KWPLs5vnvVPljAht79hFxGrH1Ozk7wBChDceXJSlN6a9r70DoXRJlLya4RGzywgkcnSjCTNB9ln6aPGF1fY47i6TN24=
